### ISSUE TITLE
"CNAME record must be the only record" error

### ISSUE THREAD

**Issue by bastien30** [octodns/octodns-gandi#16]
Hi,

When replacing an existing CNAME record by an A record, I'm getting this error : 
`CNAME record must be the only record`

I've checked the `__init__.py` file and it seems there is a workaround specific to this error : 
![image](https://github.com/octodns/octodns-gandi/assets/5484905/ed570ea0-0ae2-4e8c-9d02-8eae19d444fa)

When commenting out the `changes.reverse()` it works as expected.

Doesn't OctoDNS already perform the deletion before creation ? If so this workaround is not needed anymore ?

Thanks.

**Comment by ross** [comment]
> Doesn't OctoDNS already perform the deletion before creation ? If so this workaround is not needed anymore ?

That does seems like a work-around that just happened to do the right thing based on the order of the stuff involved at the time. I would think it'd have to be considering record type in the sorting to preserve the correct delete order. 

The PR that introduced change ordering is https://github.com/octodns/octodns/commit/cdcaef8f2bbc1a1e47b84a61eb9935308e801218.

You wanna file a PR for gandi to remove the work-around? It should probably also require `octodns>=v0.9.17` in setup.py

**Comment by bastien30** [comment]
Hello,

Thanks for your answer.

I've tried forking/cloning the project to make a pull request, following CONTRIBUTING.md rules, but it seems the workaround removal break the tests (it passed before).

Unfortunately I don't have the skills to check that the workaround removal does not break anything else, and to update the test.
